plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.1.1.cjs

packageExtensions:
  "eslint-plugin-import@*":
    dependencies:
      "typescript": "*"
  "eslint@*":
    dependencies:
      "@typescript-eslint/parser": "*"
  "eslint-module-utils@*":
    dependencies:
      "eslint": "*"
  "react-hot-loader@*":
    dependencies:
      "@hot-loader/react-dom": "*"
  "@types/react-dom@*":
    dependencies:
      "react": "*"
  "@typescript-eslint/parser@*":
    dependencies:
      "typescript": "*"
      "eslint": "*"
